### ISSUE TITLE
Slave.rb line 246 timeout method on ruby 2.3.0

### ISSUE THREAD

**Issue by mbround18** [fernandoluizao/rmodbus#45]
Hey there,
  I am using this in a raspberry pi IoT project and with ruby 2.3.0 line 246 in the Slave.rb has a hiccup. If its changed to 'Timeout.timeout(@read_retry_timeout, ModBusTimeout' the program than functions normally.

**Comment by fernandoluizao** [comment]
The next release (1.2.8) will fix this warning. I'll push in the next days.
